# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jaya Transport Service CI/CD

on:
  push:
    tags:
      - 'v*'
      - '!v*-ubs_kalung'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Create environment production
        run: |
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sigitnurmajid/jaya-transport-service
          tags: |
            type=semver,pattern=latest,enable=${{ !contains(github.ref_name, '-') }}
            type=semver,pattern={{version}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  pull_the_registery:
      needs: push_to_registry
      name: Push Docker image to Server
      runs-on: ubuntu-latest
      if: "!contains(github.ref_name, 'ubs_kalung') && !contains(github.ref_name, 'ubs_hollow')"

      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop jaya-transport-service
            sudo docker rm jaya-transport-service

            sudo docker rmi sigitnurmajid/jaya-transport-service:latest
            sudo docker pull sigitnurmajid/jaya-transport-service:latest

            sudo docker run -t -d --restart always --network host --name jaya-transport-service sigitnurmajid/jaya-transport-service:latest
