# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jaya Transport Service CI/CD

on:
  release:
    types: [published]
  push:
    tags:
       - 'v*.*.*'

jobs:
  push_to_registry:
    if: github.event.release.target_commitish == 'ubs-build'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Create environment production
        run: |
          echo "${{ secrets.ENV_UBS_FILE_PRODUCTION }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sigitnurmajid/jaya-transport-service
          tags: |
            type=semver,pattern=latest
            type=semver,pattern={{version}}-${{ github.event.release.target_commitish }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
