# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jaya Transport Service CI/CD (UBS Kalung)

on:
  push:
    tags:
      - 'v*-ubs_kalung'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub (UBS Kalung)
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Create environment production
        run: |
          echo "${{ secrets.ENV_UBS_FILE_PRODUCTION }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sigitnurmajid/jaya-transport-service
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=latest-ubs_kalung
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
